### ISSUE TITLE
Разбиение функции на логические части

### ISSUE THREAD

**Issue by ghost** [oleggator/poszhalusta_primite_proekt#11]
Например эта [функция](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/AuthorizationController.cpp#L31)
Можно было бы разбить на несколько частей, которые связаны, например Создание элемента и установление в него значений.

**Comment by Dnnd** [comment]
Метод представляет собой цельную логическую единицу. В цельях улучшения читаемости, оформление метода изменено.
