### ISSUE TITLE
Ключи в переменных в открытом доступе

### ISSUE THREAD

**Issue by ghost** [oleggator/poszhalusta_primite_proekt#12]
https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/AuthorizationController.cpp#L12
Ключи хорошо было бы вынести в переменную среды окружения.
Так же вынести другие константы в конфиг файл.

**Comment by Dnnd** [comment]
На данный момент, нет нужды усложнять структуру проекта в этом направлении, так как нет никаких предпосылок для изменений Yandex Rest Api. Тем не менее, issue внесен во внутренний список TODO проекта.
