### ISSUE TITLE
Вынести хардкод в константу

### ISSUE THREAD

**Issue by ghost** [oleggator/poszhalusta_primite_proekt#13]
Например, [тут.](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/FileDownloader.cpp#L44)

**Comment by Dnnd** [comment]
Исправлено. Теперь каждый экземпляр класса FileDownloader содержит изменяемый суффикс для временных файлов.
