### ISSUE TITLE
Разбить функцию на несколько подфункций.

### ISSUE THREAD

**Issue by ghost** [oleggator/poszhalusta_primite_proekt#14]
[Функция](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/FileWatch.cpp#L97), которая может быть разбита на несколько.(особенно много ифов)

**Comment by DrMatters** [comment]
Рассматриваеваемую функцию удалось разбить на отдельные логические единицы
