### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by ghost** [oleggator/poszhalusta_primite_proekt#15]
[Здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/FileWatch.cpp#L41) и [здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/FileWatch.cpp#L47)

**Comment by ghost** [comment]
[Здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/RestApiBase.cpp#L135)

**Comment by Dnnd** [comment]
Исправлено. [Здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/FileWatch.cpp#L47) был изменен один из повторяющихся фрагментов. [Здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/RestApiBase.cpp#L135) метод заменен шаблоном метода
