### ISSUE TITLE
Следование единому стайлгайду

### ISSUE THREAD

**Issue by ghost** [oleggator/poszhalusta_primite_proekt#17]
[Здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/ReplyWrapper.cpp#L9) используются фигурные скобки при вызове конструктора. Выше же используются круглые.

**Comment by ghost** [comment]
[Здесь](https://github.com/oleggator/poszhalusta_primite_proekt/blob/cbbfd65d0bff19de665d7119f895592ba84f0452/src/RestApiBase.cpp#L10) нет пробелов после запятых.

**Comment by Dnnd** [comment]
Каждый файл проекта был заново обработаны при помощи средств автоформатирования Clion. Несогласованность в использовании формата скобок при вызовах конструкторов исправлена.
